services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

  frontend-dev:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge
